In [1]:
!pip install pandas numpy openpyxl sqlalchemy

Requirement already satisfied: pandas in c:\users\sayandeep\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\sayandeep\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: openpyxl in c:\users\sayandeep\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: sqlalchemy in c:\users\sayandeep\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sayandeep\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sayandeep\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sayandeep\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\sayandeep\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: greenlet>=1 in c:\users\sayandeep\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sayandeep\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\sayandeep\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_excel("Ecommerce_Unclean_Project.xlsx")

In [4]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    object
 1   Order_Date     524 non-null    object
 2   Customer_Name  524 non-null    object
 3   Email          524 non-null    object
 4   Phone          502 non-null    float64
 5   City           524 non-null    object
 6   State          524 non-null    object
 7   Product        524 non-null    object
 8   Category       524 non-null    object
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    object
 13  Order_Status   524 non-null    object
 14  Delivery_Date  503 non-null    object
dtypes: float64(3), object(12)
memory usage: 61.5+ KB

In [7]:
df.shape

(524, 15)

In [8]:
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [9]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(11)

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.replace(['N/A','NULL',' '],np.nan,inplace=True)

In [21]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15.0,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,NaN,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,NaN,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,NaN,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,NaN,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,09-03-2025

In [23]:
df=df.apply(lambda x : x.str.strip() if x.dtype=='object' else x)

In [25]:
df['Customer_Name'] = df['Customer_Name'].str.title()
df['City']=df['City'].str.title()
df['State']=df['State'].str.title()

In [26]:
df= df[df['Email'].str.contains('@', na=False)]

In [28]:
df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')
df['Delivery_Date']=pd.to_datetime(df['Delivery_Date'],errors='coerce')

C:\Users\SAYANDEEP\AppData\Local\Temp\ipykernel_18100\2369654277.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')

In [29]:
cols=['Qty','Unit_Price','Discount']
for c in cols:
    df[c]=pd.to_numeric(df[c],errors='coerce')

In [30]:
df=df[df['Qty']>0]

In [34]:
df['Discount']= df['Discount'].fillna(0)
df['Phone']=df['Phone'].fillna('Unknown',inplace=True)
df['Delivery_Date']=df['Delivery_Date'].fillna(df['Order_Date'])

C:\Users\SAYANDEEP\AppData\Local\Temp\ipykernel_18100\3391416915.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Phone']=df['Phone'].fillna('Unknown',inplace=True)

In [35]:
df['Sales']=df['Qty']*df['Unit_Price']

In [36]:
df['Net_Amount']=df['Sales']-(df['Sales']*df['Discount']/100)

In [37]:
df['Profit']=df['Net_Amount']*0.20

In [38]:
df['Month']=df['Order_Date'].dt.month_name()

In [39]:
df['Year']=df['Order_Date'].dt.year

In [40]:
df['Weekday']=df['Order_Date'].dt.day_name()

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 380 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       374 non-null    object
 1   Order_Date     333 non-null    datetime64[ns]
 2   Customer_Name  380 non-null    object
 3   Email          380 non-null    object
 4   Phone          0 non-null      object
 5   City           380 non-null    object
 6   State          380 non-null    object
 7   Product        380 non-null    object
 8   Category       380 non-null    object
 9   Qty            380 non-null    float64
 10  Unit_Price     343 non-null    float64
 11  Discount       380 non-null    float64
 12  Payment_Mode   380 non-null    object
 13  Order_Status   380 non-null    object
 14  Delivery_Date  348 non-null    datetime64[ns]
 15  Sales          343 non-null    float64
 16  Net_Amount     343 non-null    float64
 17  Profit         343 non-null    float64
 18  Month          333 non-null    object
 19  Year           333 non-null    float64
 20  Weekday        333 non-null    object
dtypes: datetime64[ns](2), float64(7), object(12)
memory usage: 65.3+ KB

In [42]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date,Sales,Net_Amount,Profit,Year
count,333,380.000000,343.000000,380.000000,348,343.000000,343.000000,343.000000,333.0
mean,2025-04-02 17:35:08.108108032,3.328947,3252.352770,7.802632,2025-05-01 04:12:24.827586304,11103.664723,10249.073324,2049.814665,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.000000,2025-01-02 00:00:00,499.000000,399.200000,79.840000,2025.0
25%,2025-02-14 00:00:00,2.000000,999.000000,0.000000,2025-02-16 18:00:00,2599.000000,2398.400000,479.680000,2025.0
50%,2025-04-05 00:00:00,3.000000,1999.000000,5.000000,2025-04-19 00:00:00,5997.000000,5996.000000,1199.200000,2025.0
75%,2025-05-16 00:00:00,5.000000,4999.000000,15.000000,2025-06-18 00:00:00,12995.000000,12995.000000,2599.000000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,20.000000,2025-12-06 00:00:00,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,1.458196,3026.092014,7.881075,NaN,12194.528486,11506.169779,2301.233956,0.0

In [45]:
df.to_csv('Clean_Ecommerce.csv',index=False)

In [46]:
pip install psycopg2.binary sqlalchemy

Requirement already satisfied: psycopg2.binary in c:\users\sayandeep\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\sayandeep\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\sayandeep\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sayandeep\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [47]:
from sqlalchemy import create_engine
username = "postgres"
password= "sayandeep12345"
host= "localhost"
port="5432"
database= "ecommerce"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name="customer"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print(f"data successfully loaded into table '{table_name}' in database '{database}'.")

data successfully loaded into table 'customer' in database 'ecommerce'.